language: node_js
node_js:
  - node

deploy:
  # add this line after travis setup
  skip_cleanup: true
  provider: npm
  email: 59022665@qq.com
  api_key: "9759d6ba-da9c-49cc-b74b-d128f9a33697"
  on:
    tags: true
    repo: buzhoumountain/masks-js

before_deploy:
  - npm run build
